什么是 PyTorch？  

PyTorch 是一个基于 Python 的科学计算包，有两大用途：

- NumPy 的替代品，可使用 GPU 和其他加速器的强大功能。
- 一个用于实现神经网络的自动微分库。

本教程的目标：
- 高层次理解 PyTorch 的 Tensor 库和神经网络。
- 训练一个小型神经网络来对图像进行分类

> note：确保您安装了torch和torchvision软件包。

In [1]:
%matplotlib inline

# Tensors

张量是一种特殊的数据结构，与数组和矩阵非常相似。在 PyTorch 中，我们使用张量对模型的输入和输出以及模型的参数进行编码。  

张量类似于 NumPy 的 ndarray，不同之处在于张量可以在 GPU 或其他专用硬件上运行以加速计算。如果您熟悉 ndarrays，那么您将熟悉 Tensor API。如果没有，请按照此快速 API 演练进行操作。

In [2]:
import torch
import numpy as np

## Tensor 初始化
创建Tensor有多种方法，如：  

1. **直接从数据创建**  
可以直接利用数据创建tensor,数据类型会被自动推断出.

In [3]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

2. **来自一个Numpy 数组**  

Tensor 可以直接从numpy的array创建（反之亦然-参见 [Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)）

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

3. **来自另一个tensor：**  
新的tensor保留了参数tensor的一些属性（形状，数据类型），除非显式覆盖

In [5]:
x_ones = torch.ones_like(x_data) # 保留x_data的属性
print(f"Ones Tensor: \n {x_ones} \n")


x_rand = torch.rand_like(x_data, dtype=torch.float) # 覆盖x_data的数据类型
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8782, 0.0328],
        [0.0179, 0.8443]]) 



4. **使用随机数或常数创建**  
shape是关于tensor维度的一个元组，在下面的函数中，它决定了输出tensor的维数。

In [6]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape) 
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n  {rand_tensor} \n")
print(f"Ones Tensor: \n  {ones_tensor} \n ")
print("Zeros Tensor: \n ", zeros_tensor, f"\n \n  {zeros_tensor} \n")


Random Tensor: 
  tensor([[0.0575, 0.9938, 0.7409],
        [0.3115, 0.4109, 0.0989]]) 

Ones Tensor: 
  tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 
Zeros Tensor: 
  tensor([[0., 0., 0.],
        [0., 0., 0.]]) 
 
  tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## Tensor 属性  
张量属性描述了它们的形状、数据类型和存储它们的设备。


In [7]:
tensor = torch.rand(shape)

print(f"Shape of tensor:{tensor.shape}")
print("Datatype of tensor: ", tensor.dtype)
print(f"Datatype of tensor: {tensor.dtype}")
print("Device tensor is stored on:", tensor.device)
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor:torch.Size([2, 3])
Datatype of tensor:  torch.float32
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Device tensor is stored on: cpu


## Tensor 运算  
Tensor有超过100个操作，包括 transposing, indexing, slicing, mathematical operations, linear algebra, random sampling,更多详细的介绍请点击[这里](https://pytorch.org/docs/stable/torch.html) 

它们都可以在GPU上运行（速度通常比CPU快），如果你使用的是Colab，通过编辑>笔记本设置来分配一个GPU。

In [8]:
# 如果有GPU的话，我们把Tensor移到GPU上

if torch.cuda.is_available(): 
    tensor = tensor.to("cuda")
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


尝试列表中的一些操作。如果你熟悉NumPy API，你会发现tensor的API很容易使用。

**标准的numpy类索引和切片:**

In [9]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0 
print(tensor)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**合并 Tensor**  
可以使用torch.cat来沿着特定维数连接一系列张量。 torch.stack另一个加入op的张量与torch.cat有细微的不同


In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) # dim=0
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

**Tensor 乘积**  


In [11]:
# 这将计算元素的乘积
print(f"tensor.mul(tensor): \n  {tensor.mul(tensor)} \n")
# 替代语法：
tensor * tensor

tensor.mul(tensor): 
  tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

下面示例计算两个tensor之间的矩阵乘法

In [12]:
print(tensor.matmul(tensor.T), f'\n')
# 替代语法：
print(tensor @ tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


**原地操作**  
带有后缀_的操作表示的是原地操作，例如： x.copy_(y), x.t_()将改变 x.

In [13]:
print(tensor, "\n")
tensor.add_(5)
tensor


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

- 注意  
原地操作虽然会节省许多空间，但是由于会立刻清除历史记录所以在计算导数时可能会有问题，因此不建议使用

## Tensor 与 Numpy 桥梁  
在CPU上的 Tensor和 NumPy arrays 可以共享它们的底层内存位置，改变一个会改变另一个。

**Tensor转换为Numpt 数组**   


In [14]:
t = torch.ones(5)
print(f"t: {t} \n ")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.]) 
 
n: [1. 1. 1. 1. 1.]


Tensor的变化反映在NumPy数组中。

In [15]:
t.add_(1)
print(f"t: {t} \n")
print(f"n: {n}")


t: tensor([2., 2., 2., 2., 2.]) 

n: [2. 2. 2. 2. 2.]


**Numpy数组转换为Tensor**

In [16]:
n = np.ones(5)
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

NumPy数组的变化反映在tensor中

In [17]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
