什么是 PyTorch？  

PyTorch 是一个基于 Python 的科学计算包，有两大用途：

- NumPy 的替代品，可使用 GPU 和其他加速器的强大功能。
- 一个用于实现神经网络的自动微分库。

本教程的目标：
- 高层次理解 PyTorch 的 Tensor 库和神经网络。
- 训练一个小型神经网络来对图像进行分类

> note：确保您安装了torch和torchvision软件包。

In [1]:
%matplotlib inline

# Tensors

张量是一种特殊的数据结构，与数组和矩阵非常相似。在 PyTorch 中，我们使用张量对模型的输入和输出以及模型的参数进行编码。  

张量类似于 NumPy 的 ndarray，不同之处在于张量可以在 GPU 或其他专用硬件上运行以加速计算。如果您熟悉 ndarrays，那么您将熟悉 Tensor API。如果没有，请按照此快速 API 演练进行操作。

In [2]:
import torch
import numpy as np

## Tensor 初始化
创建Tensor有多种方法，如：  

1. **直接从数据创建**  
可以直接利用数据创建tensor,数据类型会被自动推断出.

In [3]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

2. **来自一个Numpy 数组**  

Tensor 可以直接从numpy的array创建（反之亦然-参见 [Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)）

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

3. **来自另一个tensor：**  
新的tensor保留了参数tensor的一些属性（形状，数据类型），除非显式覆盖

In [5]:
x_ones = torch.ones_like(x_data) # 保留x_data的属性
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # 覆盖x_data的数据类型
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3306, 0.7151],
        [0.5787, 0.3512]]) 

